services:
  kernel-build:
    privileged: true
    tty: true
    hostname: "DOCKER-BOX"
    environment:
      - DISPLAY
    build:
      context: .
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
      dockerfile: ./Dockerfile
    image: pohmsuindraguli/kernel-dev:latest
    command: /bin/bash
    stdin_open: true
    volumes:
      - ../kernel-workspace:/linux
